"""Symbol loading and management module for P&ID generation.

Scans the symbols folder dynamically (no hardcoded registry.json dependency),
indexes symbols by category/subcategory, computes anchor points from snap
points, and maps graph class IDs to real SVG symbols.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

# Base path for symbols (relative to this file)
_SYMBOLS_BASE = Path(__file__).parent.parent / "symbols"

# Mapping: graph class_id → ordered list of (category, subcategory) preferences.
# A subcategory of None means "any symbol in that category".
# Based on class IDs generated by graph_builder.py and available ISA symbols.
_CLASS_ID_TO_CATEGORIES: dict[int, list[tuple[str, str | None]]] = {
    # Check valve → rotary_valve shape has 2 in_out pts
    2:  [("valve", "rotary_valve")],
    # Control valve (from control loops)
    3:  [("valve", "control_valve"), ("valve", "a_control_valve")],
    # Isolation valves (gate, globe, ball, butterfly, plug, angle)
    4:  [("valve", "gate_valve")],
    5:  [("valve", "gate_valve"), ("valve", "globe")],
    6:  [("valve", "hand_valve")],
    7:  [("valve", "globe")],
    9:  [("valve", "hand_valve"), ("valve", "gate_valve")],
    10: [("valve", "rotary_valve")],
    11: [("valve", "globe"), ("valve", "hand_valve")],
    # Pumps (centrifugal)
    24: [("equipment", "compressor")],
    25: [("equipment", "compressor")],
    # Inline process equipment
    26: [("equipment", "exchanger_heat_exchanger1")],
    27: [("equipment", "reactor")],
    28: [("equipment", "exchanger_heat_exchanger1"), ("equipment", "reactor")],
    29: [("equipment", "reactor"), ("equipment", "exchanger_heat_exchanger1")],
    # Storage tanks / receivers
    30: [("equipment", "tank_jacketed_vessel")],
    31: [("equipment", "tank_jacketed_vessel")],
    # Strainer / flow elements
    34: [("flow", "orifice"), ("relief_valve", "flow_orifice")],
}


def list_available_standards() -> list[str]:
    """Return the list of symbol standards found in the symbols folder."""
    if not _SYMBOLS_BASE.exists():
        return []
    return sorted(
        p.name for p in _SYMBOLS_BASE.iterdir()
        if p.is_dir() and any(p.rglob("*.json"))
    )


class SymbolRegistry:
    """Dynamically scanned P&ID symbol registry.

    Scans ``symbols/{standard}/`` at construction time (no registry.json
    dependency). Symbols are indexed by ID, category, and subcategory for
    fast lookup.
    """

    def __init__(self, standard: str = "isa") -> None:
        self.standard = standard.lower()
        # id → full metadata dict
        self.symbols: dict[str, dict[str, Any]] = {}
        # category → [symbol, ...]
        self._by_category: dict[str, list[dict[str, Any]]] = {}
        # (category, subcategory) → [symbol, ...]
        self._by_cat_sub: dict[tuple[str, str], list[dict[str, Any]]] = {}
        self._scan()

    # ------------------------------------------------------------------
    # Internal scanning
    # ------------------------------------------------------------------

    def _scan(self) -> None:
        """Recursively scan ``symbols/{standard}/**/*.json`` and index them."""
        std_dir = _SYMBOLS_BASE / self.standard
        if not std_dir.exists():
            print(f"Warning: Symbol directory not found: {std_dir}")
            return

        count = 0
        for json_path in sorted(std_dir.rglob("*.json")):
            try:
                with open(json_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
            except (json.JSONDecodeError, OSError):
                continue

            symbol_id = data.get("id", "")
            if not symbol_id:
                continue

            self.symbols[symbol_id] = data
            count += 1

            cat = data.get("category", "").lower()
            sub = data.get("subcategory", "").lower()
            if cat:
                self._by_category.setdefault(cat, []).append(data)
                self._by_cat_sub.setdefault((cat, sub), []).append(data)

        if count == 0:
            print(f"Warning: No symbols found for standard '{self.standard}'")

    # ------------------------------------------------------------------
    # Anchor computation
    # ------------------------------------------------------------------

    def compute_anchor(self, symbol: dict[str, Any]) -> tuple[float, float]:
        """Return the normalised anchor of a symbol's in_out snap points.

        The anchor is the centroid of all ``"in_out"`` snap points, expressed
        as a fraction of the SVG viewBox (0 = left/top edge, 1 = right/bottom).
        Falls back to ``(0.5, 0.5)`` if no in_out points or bad viewBox.
        """
        snap_points = symbol.get("snap_points", [])
        in_out = [(s["x"], s["y"]) for s in snap_points if s.get("type") == "in_out"]

        if not in_out:
            return (0.5, 0.5)

        vb = symbol.get("svg", {}).get("view_box", "")
        try:
            parts = vb.split()
            vb_w, vb_h = float(parts[2]), float(parts[3])
        except (ValueError, IndexError, AttributeError):
            return (0.5, 0.5)

        if vb_w <= 0 or vb_h <= 0:
            return (0.5, 0.5)

        ax = sum(p[0] for p in in_out) / len(in_out) / vb_w
        ay = sum(p[1] for p in in_out) / len(in_out) / vb_h
        return (max(0.0, min(1.0, ax)), max(0.0, min(1.0, ay)))

    def get_normalised_snap_points(
        self, symbol: dict[str, Any]
    ) -> list[dict[str, Any]]:
        """Return all snap points with ``nx`` / ``ny`` normalised coordinates added.

        Each returned dict contains the original fields plus:
        - ``nx``: x in [0, 1] (x / viewBox_width)
        - ``ny``: y in [0, 1] (y / viewBox_height)
        """
        vb = symbol.get("svg", {}).get("view_box", "")
        try:
            parts = vb.split()
            vb_w, vb_h = float(parts[2]), float(parts[3])
        except (ValueError, IndexError, AttributeError):
            return []

        if vb_w <= 0 or vb_h <= 0:
            return []

        result = []
        for sp in symbol.get("snap_points", []):
            entry = dict(sp)
            entry["nx"] = sp["x"] / vb_w
            entry["ny"] = sp["y"] / vb_h
            result.append(entry)
        return result

    # ------------------------------------------------------------------
    # Symbol lookup
    # ------------------------------------------------------------------

    def get_symbol_for_class_id(
        self,
        class_id: int,
        rng: Any = None,
    ) -> dict[str, Any] | None:
        """Return a symbol for *class_id*, using *rng* to pick among candidates.

        Uses ``_CLASS_ID_TO_CATEGORIES`` to match class IDs to categories.
        When multiple candidates exist, *rng* (a ``random.Random`` instance)
        selects one; if *rng* is ``None``, the first candidate is returned.
        """
        prefs = _CLASS_ID_TO_CATEGORIES.get(class_id, [])
        for cat, sub in prefs:
            if sub:
                candidates = self._by_cat_sub.get((cat, sub), [])
            else:
                candidates = self._by_category.get(cat, [])
            if candidates:
                return rng.choice(candidates) if rng is not None else candidates[0]
        return None

    def get_symbol_by_id(self, symbol_id: str) -> dict[str, Any] | None:
        """Get a symbol by its full ID string."""
        return self.symbols.get(symbol_id)

    # Keep old name for backward compatibility
    def get_symbols_by_class_id(self, class_id: int) -> list[dict[str, Any]]:
        """Return all candidate symbols for *class_id* (backward compat)."""
        prefs = _CLASS_ID_TO_CATEGORIES.get(class_id, [])
        for cat, sub in prefs:
            if sub:
                candidates = self._by_cat_sub.get((cat, sub), [])
            else:
                candidates = self._by_category.get(cat, [])
            if candidates:
                return candidates
        return []

    def get_svg_path(self, symbol: dict[str, Any]) -> Path | None:
        """Return the absolute SVG file path for *symbol*, or ``None``."""
        # Prefer the relative svg_path stored in the JSON
        svg_path_rel = symbol.get("svg_path", "")
        if svg_path_rel:
            p = _SYMBOLS_BASE / svg_path_rel
            if p.exists():
                return p

        # Fallback: construct from standard / category / filename
        standard = symbol.get("standard", "").lower()
        category = symbol.get("category", "").lower()
        filename = symbol.get("filename", "")
        if standard and category and filename:
            p = _SYMBOLS_BASE / standard / category / filename
            if p.exists():
                return p

        return None

    # ------------------------------------------------------------------
    # Introspection helpers
    # ------------------------------------------------------------------

    def list_categories(self) -> list[str]:
        """List all available symbol categories."""
        return sorted(self._by_category.keys())

    def list_symbols_in_category(self, category: str) -> list[dict[str, Any]]:
        """List all symbols in *category*."""
        return self._by_category.get(category.lower(), [])

    def get_stats(self) -> dict[str, Any]:
        """Return statistics about the loaded symbols."""
        by_cat: dict[str, int] = {
            cat: len(syms) for cat, syms in self._by_category.items()
        }
        return {
            "standard": self.standard,
            "total_symbols": len(self.symbols),
            "categories": by_cat,
        }


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

_default_registry: SymbolRegistry | None = None


def get_registry(standard: str = "isa") -> SymbolRegistry:
    """Return (or create) the cached registry for *standard*."""
    global _default_registry
    if _default_registry is None or _default_registry.standard != standard.lower():
        _default_registry = SymbolRegistry(standard=standard)
    return _default_registry
